repos:
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v17.0.6  # versión de clang-format (ajústala a la que uses)
    hooks:
      - id: clang-format
        args: [--style=file]  # usará el archivo .clang-format de tu proyecto
        types_or: [c, c++]    # aplica solo a archivos C y C++
